name: Build Release

on: workflow_dispatch

env:
  NODE_VERSION: v16.14.0

jobs:
  Android:
    strategy:
      matrix:
        arch: [arm64, arm, x86_64, x86]
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install tools
      run: sudo apt-get install g++ gcc make gcc-multilib g++-multilib lib32z1 python3-pip python3-dev -y

    - uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r20b

    - name: Download Node.js tarball
      run: curl https://nodejs.org/dist/${NODE_VERSION}/node-${NODE_VERSION}.tar.gz | tar -xz  -C ./ && mv node-${NODE_VERSION} node

    - name: Build Node.js
      env:
        ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      run: ./scripts/build_android.sh ${{ matrix.arch }}

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: libnode-${{ env.NODE_VERSION }}-android.zip
        path: ./artifacts/android

  macOS:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install tools
      run: brew install coreutils

    - name: Download Node.js tarball
      run: curl https://nodejs.org/dist/${NODE_VERSION}/node-${NODE_VERSION}.tar.gz | tar -xz  -C ./ && mv node-${NODE_VERSION} node

    - name: Build Node.js
      run: ./scripts/build_macos.sh

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: libnode-${{ env.NODE_VERSION }}-macos-x86_64.zip
        path: ./artifacts/macos
