name: Build Android(arm64-v8a)

on: workflow_dispatch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build artifacts for Android
      uses: ./
      with:
        entrypoint: /bin/bash
        args: mkdir -p ./artifacts/android; ./scripts/patch.sh apply -f; ./scripts/build_android.sh arm64 ./artifacts/android
