name: Release

on: 
  push:
    tags:
      - "v*"
jobs:
  Build:
    uses: ./.github/workflows/build.yml
  Release:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: ./
      - name: Zip Artifacts
        run: |
          mkdir archived
          ls -d1 *.zip | xargs -I name sh -c "cd name; zip -r ../archived/name ./; cd .."
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          files: "./archived/*.zip"
          generate_release_notes: true

