name: Release

on: 
  push:
    tags:
      - "v*"
jobs:
  Build:
    uses: ./.github/workflows/build.yml
  Release:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: ./
      - name: Display structure of downloaded files
        run: ls -R ./artifacts
      - name: Zip Artifacts
        run: |
          mkdir archived
          ls -d1 *.zip | xargs -I name sh -c "pushd name; zip -r ../archived/name ./; popd"
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "./archived/*.zip"
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}

