name: Release

on: 
  push:
    tags:
      - "v*"
jobs:
  Build:
    uses: ./.github/workflows/build.yml
  Release:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          path: ./artifacts
      - name: Display structure of downloaded files
        run: ls -R ./artifacts
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "./artifacts/*.zip"
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}

